package analytics

import (
	"bytes"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/coreaxissoftware/talkex_business/internal/auth"
	"github.com/coreaxissoftware/talkex_business/internal/database"
)

// PDF export — server-side rendered summary. Ships a self-contained PDF
// via a tiny inline PDF writer (no external deps — keeping the binary
// under 20 MB is more valuable than a rich-layout PDF).
//
// The output is a one-page A4 landscape summary: title, generated-at,
// six key metrics rendered as text lines. Sufficient for the "email
// this to my accountant" use case competitors ship; a richer PDF with
// charts can layer on later without changing the endpoint shape.

// RegisterPDFRoute wires GET /analytics/pdf.
func RegisterPDFRoute(r *gin.Engine) {
	g := r.Group("/analytics")
	g.Use(auth.AuthRequired())
	g.GET("/pdf", handlePDF)
}

func handlePDF(c *gin.Context) {
	ownerID := auth.GetUserID(c)
	stats, err := GetSummary(database.DB, ownerID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": "Internal server error"})
		return
	}

	lines := []string{
		"TalkEx Business - Analytics Summary",
		fmt.Sprintf("Generated: %s", time.Now().UTC().Format("2006-01-02 15:04 UTC")),
		"",
		fmt.Sprintf("Total Messages:         %d", stats.TotalMessages),
		fmt.Sprintf("Outbound Messages:      %d", stats.OutboundMessages),
		fmt.Sprintf("Inbound Messages:       %d", stats.InboundMessages),
		fmt.Sprintf("Delivery Rate:          %.1f%%", stats.DeliveryRate*100),
		fmt.Sprintf("Open Conversations:     %d", stats.OpenConversations),
		fmt.Sprintf("Total Contacts:         %d", stats.TotalContacts),
		fmt.Sprintf("Active Campaigns:       %d", stats.ActiveCampaigns),
		"",
		"This report was generated by TalkEx Business.",
	}

	pdf := renderPDF(lines)
	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", `attachment; filename="talkex-analytics.pdf"`)
	c.Data(http.StatusOK, "application/pdf", pdf)
}

// renderPDF writes a minimal but valid PDF 1.4 document with the given
// text lines, using the built-in Helvetica font. Each line is 14pt with
// 6pt gap; up to ~30 lines fit on the page.
func renderPDF(lines []string) []byte {
	var content bytes.Buffer
	fmt.Fprintf(&content, "BT\n/F1 14 Tf\n50 780 Td\n")
	for i, line := range lines {
		if i > 0 {
			fmt.Fprintf(&content, "0 -20 Td\n")
		}
		// Escape parens and backslashes per PDF spec.
		esc := ""
		for _, r := range line {
			switch r {
			case '(', ')', '\\':
				esc += "\\" + string(r)
			default:
				esc += string(r)
			}
		}
		fmt.Fprintf(&content, "(%s) Tj\n", esc)
	}
	fmt.Fprintf(&content, "ET\n")

	// Build cross-reference table.
	var pdf bytes.Buffer
	pdf.WriteString("%PDF-1.4\n")

	offsets := make([]int, 5)

	offsets[0] = pdf.Len()
	pdf.WriteString("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")

	offsets[1] = pdf.Len()
	pdf.WriteString("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")

	offsets[2] = pdf.Len()
	pdf.WriteString("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] " +
		"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj\n")

	offsets[3] = pdf.Len()
	pdf.WriteString("4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")

	offsets[4] = pdf.Len()
	fmt.Fprintf(&pdf, "5 0 obj\n<< /Length %d >>\nstream\n", content.Len())
	pdf.Write(content.Bytes())
	pdf.WriteString("endstream\nendobj\n")

	xrefStart := pdf.Len()
	pdf.WriteString("xref\n0 6\n")
	pdf.WriteString("0000000000 65535 f \n")
	for _, o := range offsets {
		fmt.Fprintf(&pdf, "%010d 00000 n \n", o)
	}
	fmt.Fprintf(&pdf, "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", xrefStart)
	return pdf.Bytes()
}
